project_id = "besjfzlgtssriqpluzgn"

[functions.create-demo-artist]
verify_jwt = false

[functions.complete-artist-signup]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-update-role]
verify_jwt = true

[functions.analyze-portfolio-image]
verify_jwt = false

[functions.sadad-initiate-payment]
verify_jwt = true

[functions.sadad-payment-callback]
verify_jwt = false

[functions.translate-service]
verify_jwt = true

[functions.create-artist-invitation]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.public-seller-signup]
verify_jwt = true
